"""Added models for push notifications

Revision ID: 05c24dbd64cf
Revises: fbfe32bcca6d
Create Date: 2025-08-25 11:03:04.157924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05c24dbd64cf'
down_revision = 'fbfe32bcca6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('push_subscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subscription_json', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('league_entries', schema=None) as batch_op:
        batch_op.drop_column('current_rank')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('league_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_rank', sa.INTEGER(), autoincrement=False, nullable=True))

    op.drop_table('push_subscription')
    # ### end Alembic commands ###
