"""Add fee_collected to LeagueEntry

Revision ID: 066435ee5a26
Revises: 05c24dbd64cf
Create Date: 2025-09-16 13:09:17.554968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '066435ee5a26'
down_revision = '05c24dbd64cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('league_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fee_collected', sa.Boolean(), nullable=False, server_default='false'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('league_entries', schema=None) as batch_op:
        batch_op.drop_column('fee_collected')

    # ### end Alembic commands ###
