"""aded custom rules to league creation

Revision ID: 08ce58f58d28
Revises: 2e03ccc92cff
Create Date: 2025-08-09 13:04:35.434184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08ce58f58d28'
down_revision = '2e03ccc92cff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leagues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_entries', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('odds_limit', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('no_favorites_rule', sa.Integer(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leagues', schema=None) as batch_op:
        batch_op.drop_column('no_favorites_rule')
        batch_op.drop_column('odds_limit')
        batch_op.drop_column('max_entries')

    # ### end Alembic commands ###
