"""Add User, Club models and update League/Entry

Revision ID: 153cddaf70ee
Revises: ab7b4de8693f
Create Date: 2025-07-20 18:52:43.970979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '153cddaf70ee'
down_revision = 'ab7b4de8693f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clubs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('club_name', sa.String(length=150), nullable=False),
    sa.Column('contact_person', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('website', sa.String(length=200), nullable=True),
    sa.Column('address', sa.String(length=250), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('club_name'),
    sa.UniqueConstraint('email')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('is_club_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('league_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('leagues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('league_code', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('entry_fee', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('prize_details', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('rules', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('club_id', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint(None, ['league_code'])
        batch_op.create_foreign_key(None, 'clubs', ['club_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leagues', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('club_id')
        batch_op.drop_column('rules')
        batch_op.drop_column('prize_details')
        batch_op.drop_column('entry_fee')
        batch_op.drop_column('league_code')

    with op.batch_alter_table('league_entries', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    op.drop_table('users')
    op.drop_table('clubs')
    # ### end Alembic commands ###
