"""Added dg_id to player model

Revision ID: 156b373e87eb
Revises: e2e79d65f0f3
Create Date: 2025-08-07 20:45:58.194187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '156b373e87eb'
down_revision = 'e2e79d65f0f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dg_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(None, ['dg_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('dg_id')

    # ### end Alembic commands ###
