"""Add password reset flag to user and club models

Revision ID: 19226f22326c
Revises: a492d476d768
Create Date: 2025-08-05 15:36:43.043819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19226f22326c'
down_revision = 'a492d476d768'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clubs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_reset_required', sa.Boolean(), nullable=False))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_reset_required', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('password_reset_required')

    with op.batch_alter_table('clubs', schema=None) as batch_op:
        batch_op.drop_column('password_reset_required')

    # ### end Alembic commands ###
