"""Added tips to clubs

Revision ID: 1e28fab99068
Revises: d7ea8b46bdf7
Create Date: 2025-10-07 16:35:03.371717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e28fab99068'
down_revision = 'd7ea8b46bdf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clubs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tips_dismissed', sa.JSON(), nullable=True))

    with op.batch_alter_table('league_templates', schema=None) as batch_op:
        batch_op.create_index('idx_template_name', ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('league_templates', schema=None) as batch_op:
        batch_op.drop_index('idx_template_name')

    with op.batch_alter_table('clubs', schema=None) as batch_op:
        batch_op.drop_column('tips_dismissed')

    # ### end Alembic commands ###
