"""Add tie_breaker_answer to LeagueEntry

Revision ID: 203751609609
Revises: 4982e2e47b69
Create Date: 2025-07-20 22:23:29.640014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '203751609609'
down_revision = '4982e2e47b69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('league_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tie_breaker_answer', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('league_entries', schema=None) as batch_op:
        batch_op.drop_column('tie_breaker_answer')

    # ### end Alembic commands ###
