"""added prize amount to league modal

Revision ID: 2e03ccc92cff
Revises: 4fa36d75d8c5
Create Date: 2025-08-09 12:34:00.179974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e03ccc92cff'
down_revision = '4fa36d75d8c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leagues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prize_amount', sa.Float(), server_default='0.0', nullable=False))
        batch_op.alter_column('payout_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leagues', schema=None) as batch_op:
        batch_op.alter_column('payout_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
        batch_op.drop_column('prize_amount')

    # ### end Alembic commands ###
