"""Updated player model. added tee time

Revision ID: 344766eb95fe
Revises: 116a311e8105
Create Date: 2025-08-07 14:55:39.508521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '344766eb95fe'
down_revision = '116a311e8105'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tee_time', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_column('tee_time')

    # ### end Alembic commands ###
