"""Added total_winnings to user

Revision ID: 39bfd17b28eb
Revises: 156b373e87eb
Create Date: 2025-08-08 14:24:09.800208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39bfd17b28eb'
down_revision = '156b373e87eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_winnings', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('total_winnings')

    # ### end Alembic commands ###
