"""Remove entry_name from LeagueEntry, add display_entry_name property

Revision ID: 4982e2e47b69
Revises: 967b9b03bf2c
Create Date: 2025-07-20 21:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4982e2e47b69'
down_revision = '967b9b03bf2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Step 1: Add 'tie_breaker_question' column to 'leagues' as nullable first
    with op.batch_alter_table('leagues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tie_breaker_question', sa.String(length=255), nullable=True))

    # Step 2: Update existing rows with a default value for 'tie_breaker_question'
    # This ensures no NULL values when we make it NOT NULL
    op.execute(
        "UPDATE leagues SET tie_breaker_question = 'How many total shots will Rory McIlroy take to complete the 4 days of the tournament?' WHERE tie_breaker_question IS NULL"
    )

    # Step 3: Alter 'tie_breaker_question' column to be NOT NULL
    with op.batch_alter_table('leagues', schema=None) as batch_op:
        batch_op.alter_column('tie_breaker_question',
                              existing_type=sa.String(length=255),
                              type_=sa.String(length=255), # ADDED: Explicitly define the new type
                              nullable=False,
                              existing_nullable=True,
                              postgresql_using="tie_breaker_question::varchar(255)") # Ensure type casting for PostgreSQL

    # Remove 'entry_name' from 'league_entries'
    with op.batch_alter_table('league_entries', schema=None) as batch_op:
        batch_op.drop_column('entry_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Re-add 'entry_name' to 'league_entries' (nullable, you might need to handle defaults if re-populating)
    with op.batch_alter_table('league_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entry_name', sa.String(length=100), nullable=True)) # Make nullable on downgrade

    # Remove 'tie_breaker_question' from 'leagues'
    with op.batch_alter_table('leagues', schema=None) as batch_op:
        batch_op.drop_column('tie_breaker_question')

    # ### end Alembic commands ###
