"""added stripe account id to user and club

Revision ID: 4fa36d75d8c5
Revises: 39bfd17b28eb
Create Date: 2025-08-09 12:19:26.041539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fa36d75d8c5'
down_revision = '39bfd17b28eb'
branch_labels = None
depends_on = None


def upgrade():
     # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clubs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_account_id', sa.String(length=255), nullable=True))

    with op.batch_alter_table('leagues', schema=None) as batch_op:
        # --- THIS IS THE LINE TO EDIT ---
        batch_op.add_column(sa.Column('payout_status', sa.String(length=20), server_default='pending', nullable=False))
        # --- END OF EDIT ---

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_account_id', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('stripe_account_id')

    with op.batch_alter_table('leagues', schema=None) as batch_op:
        batch_op.drop_column('payout_status')

    with op.batch_alter_table('clubs', schema=None) as batch_op:
        batch_op.drop_column('stripe_account_id')

    # ### end Alembic commands ###
