"""added entry deadlin to league model

Revision ID: 4fddb73d0628
Revises: 7b965637dc6d
Create Date: 2025-09-30 11:30:55.580794

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import text


# revision identifiers, used by Alembic.
revision = '4fddb73d0628'
down_revision = '7b965637dc6d'
branch_labels = None
depends_on = None


def upgrade():
    # Add the new column (nullable initially)
    op.add_column('leagues', sa.Column('entry_deadline', sa.DateTime(), nullable=True))

    # Populate existing leagues with calculated deadline (12 hours before start_date)
    op.execute(text("""
        UPDATE leagues
        SET entry_deadline = start_date - INTERVAL '12 hours'
        WHERE entry_deadline IS NULL
    """))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leagues', schema=None) as batch_op:
        batch_op.drop_column('entry_deadline')

    # ### end Alembic commands ###
