"""add prize_details to templates

Revision ID: 50499ac39d7c
Revises: cd5ff252b07f
Create Date: 2025-10-10 10:18:27.534521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50499ac39d7c'
down_revision = 'cd5ff252b07f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('league_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prize_details', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('league_templates', schema=None) as batch_op:
        batch_op.drop_column('prize_details')

    # ### end Alembic commands ###
