"""Change prize_amount to integer for percentage

Revision ID: 5087c4e1f9dc
Revises: 59d8e66f5cf7
Create Date: 2025-08-15 10:41:58.967158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5087c4e1f9dc'
down_revision = '59d8e66f5cf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
   with op.batch_alter_table('leagues', schema=None) as batch_op:
        # This tells PostgreSQL to change the column type to INTEGER
        # and to convert the existing values using a CAST.
        batch_op.alter_column('prize_amount',
            existing_type=sa.Numeric(precision=10, scale=2),
            type_=sa.Integer(),
            postgresql_using='prize_amount::integer')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leagues', schema=None) as batch_op:
        batch_op.alter_column('prize_amount',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False,
               existing_server_default=sa.text("'0'::double precision"))

    # ### end Alembic commands ###
