"""updated league model

Revision ID: 597721002203
Revises: c404f039597f
Create Date: 2025-08-01 10:12:09.300731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '597721002203'
down_revision = 'c404f039597f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leagues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('league_code', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('entry_fee', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('prize_details', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('rules', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('tie_breaker_question', sa.String(length=255), nullable=False))
        batch_op.create_unique_constraint(None, ['league_code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leagues', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('tie_breaker_question')
        batch_op.drop_column('rules')
        batch_op.drop_column('prize_details')
        batch_op.drop_column('entry_fee')
        batch_op.drop_column('league_code')

    # ### end Alembic commands ###
