"""Add is_site_admin to user

Revision ID: 5c0f159bb48e
Revises: e85c2e6beb50
Create Date: 2025-07-22 16:21:25.012058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c0f159bb48e'
down_revision = 'e85c2e6beb50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_site_admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_site_admin')

    # ### end Alembic commands ###
