"""Add site_admin foreign key to leagues

Revision ID: 7156eb5816ad
Revises: 0e86687e8e84
Create Date: 2025-08-19 09:17:32.731953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7156eb5816ad'
down_revision = '0e86687e8e84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leagues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('site_admin_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'site_admins', ['site_admin_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leagues', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('site_admin_id')

    # ### end Alembic commands ###
