"""Add created_at to LeagueEntry model

Revision ID: 7918245e3d48
Revises: ece4c0e9a159
Create Date: 2025-08-15 14:37:02.718322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7918245e3d48'
down_revision = 'ece4c0e9a159'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('league_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('league_entries', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
