"""email rank notification added to user model

Revision ID: 7b965637dc6d
Revises: 230fc38d99f8
Create Date: 2025-09-26 12:12:50.941468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b965637dc6d'
down_revision = '230fc38d99f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_activities_activity_type'))
        batch_op.drop_index(batch_op.f('ix_user_activities_created_at'))
        batch_op.drop_index(batch_op.f('ix_user_activities_user_id'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('email_league_updates')
        batch_op.drop_column('email_achievements')
        batch_op.drop_column('email_tournament_results')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_tournament_results', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('email_achievements', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('email_league_updates', sa.BOOLEAN(), autoincrement=False, nullable=False))

    with op.batch_alter_table('user_activities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_activities_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_activities_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_activities_activity_type'), ['activity_type'], unique=False)

    # ### end Alembic commands ###
