"""Add created_at to PlayerBucket

Revision ID: 9a54988486f7
Revises: 08ce58f58d28
Create Date: 2025-08-13 15:44:23.242662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a54988486f7'
down_revision = '08ce58f58d28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_buckets', schema=None) as batch_op:
        # Add a server_default to handle existing rows
        batch_op.add_column(sa.Column('created_at', sa.DateTime(),
               nullable=False, server_default=sa.func.now()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_buckets', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
