"""Implement many-to-many for Player and PlayerBucket

Revision ID: 9f7515b76fc0
Revises: 203751609609
Create Date: 2025-07-21 12:57:24.068628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f7515b76fc0'
down_revision = '203751609609'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_buckets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('site_admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('player_bucket_association',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('player_bucket_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_bucket_id'], ['player_buckets.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('player_id', 'player_bucket_id')
    )
    with op.batch_alter_table('leagues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('player_bucket_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'player_buckets', ['player_bucket_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leagues', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('player_bucket_id')

    op.drop_table('player_bucket_association')
    op.drop_table('site_admins')
    op.drop_table('player_buckets')
    # ### end Alembic commands ###
