"""Add finalization fields to League model

Revision ID: c404f039597f
Revises: 1fb64a5f71b5
Create Date: 2025-08-01 09:33:17.863171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c404f039597f'
down_revision = '1fb64a5f71b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leagues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_finalized', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('tie_breaker_actual_answer', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('winner_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('leagues_league_code_key'), type_='unique')
        batch_op.create_foreign_key(None, 'users', ['winner_id'], ['id'])
        batch_op.drop_column('league_code')
        batch_op.drop_column('rules')
        batch_op.drop_column('prize_details')
        batch_op.drop_column('tie_breaker_question')
        batch_op.drop_column('entry_fee')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leagues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entry_fee', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('tie_breaker_question', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('prize_details', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('rules', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('league_code', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_unique_constraint(batch_op.f('leagues_league_code_key'), ['league_code'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('winner_id')
        batch_op.drop_column('tie_breaker_actual_answer')
        batch_op.drop_column('is_finalized')

    # ### end Alembic commands ###
