"""Add database indexes for performance

Revision ID: c84025fad242
Revises: b5c31bb6665e
Create Date: 2025-09-21 03:55:48.112010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c84025fad242'
down_revision = 'b5c31bb6665e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('push_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subscription_json', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('push_subscriptions', schema=None) as batch_op:
        batch_op.create_index('idx_push_user', ['user_id'], unique=False)

    op.drop_table('push_subscription')
    with op.batch_alter_table('clubs', schema=None) as batch_op:
        batch_op.create_index('idx_club_active', ['is_active'], unique=False)
        batch_op.create_index('idx_club_email', ['email'], unique=False)
        batch_op.create_index('idx_club_name', ['club_name'], unique=False)

    with op.batch_alter_table('daily_task_tracker', schema=None) as batch_op:
        batch_op.create_index('idx_task_created', ['created_at'], unique=False)
        batch_op.create_index('idx_task_date', ['task_name', 'run_date'], unique=False)

    with op.batch_alter_table('league_entries', schema=None) as batch_op:
        batch_op.create_index('idx_entry_created', ['created_at'], unique=False)
        batch_op.create_index('idx_entry_fee_status', ['fee_collected'], unique=False)
        batch_op.create_index('idx_entry_league', ['league_id'], unique=False)
        batch_op.create_index('idx_entry_league_user', ['league_id', 'user_id'], unique=False)
        batch_op.create_index('idx_entry_players', ['player1_id', 'player2_id', 'player3_id'], unique=False)
        batch_op.create_index('idx_entry_user', ['user_id'], unique=False)

    with op.batch_alter_table('leagues', schema=None) as batch_op:
        batch_op.create_index('idx_league_active', ['start_date', 'end_date', 'is_finalized'], unique=False)
        batch_op.create_index('idx_league_club', ['club_id'], unique=False)
        batch_op.create_index('idx_league_code', ['league_code'], unique=False)
        batch_op.create_index('idx_league_creator', ['creator_id'], unique=False)
        batch_op.create_index('idx_league_dates', ['start_date', 'end_date'], unique=False)
        batch_op.create_index('idx_league_fees', ['fees_processed'], unique=False)
        batch_op.create_index('idx_league_payout', ['payout_status'], unique=False)
        batch_op.create_index('idx_league_public', ['is_public'], unique=False)
        batch_op.create_index('idx_league_status', ['is_finalized'], unique=False)
        batch_op.create_index('idx_league_tour', ['tour'], unique=False)

    with op.batch_alter_table('player_buckets', schema=None) as batch_op:
        batch_op.create_index('idx_bucket_created', ['created_at'], unique=False)
        batch_op.create_index('idx_bucket_event', ['event_id'], unique=False)
        batch_op.create_index('idx_bucket_tour', ['tour'], unique=False)

    with op.batch_alter_table('player_scores', schema=None) as batch_op:
        batch_op.create_index('idx_score_league', ['league_id'], unique=False)
        batch_op.create_index('idx_score_league_player', ['league_id', 'player_id'], unique=False)

    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.create_index('idx_player_dg_id', ['dg_id'], unique=False)
        batch_op.create_index('idx_player_name_search', ['name', 'surname'], unique=False)
        batch_op.create_index('idx_player_odds', ['odds'], unique=False)
        batch_op.create_index('idx_player_score', ['current_score'], unique=False)

    with op.batch_alter_table('site_admins', schema=None) as batch_op:
        batch_op.create_index('idx_admin_username', ['username'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('idx_user_active', ['is_active'], unique=False)
        batch_op.create_index('idx_user_admin_flags', ['is_club_admin', 'is_site_admin'], unique=False)
        batch_op.create_index('idx_user_email', ['email'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('idx_user_email')
        batch_op.drop_index('idx_user_admin_flags')
        batch_op.drop_index('idx_user_active')

    with op.batch_alter_table('site_admins', schema=None) as batch_op:
        batch_op.drop_index('idx_admin_username')

    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_index('idx_player_score')
        batch_op.drop_index('idx_player_odds')
        batch_op.drop_index('idx_player_name_search')
        batch_op.drop_index('idx_player_dg_id')

    with op.batch_alter_table('player_scores', schema=None) as batch_op:
        batch_op.drop_index('idx_score_league_player')
        batch_op.drop_index('idx_score_league')

    with op.batch_alter_table('player_buckets', schema=None) as batch_op:
        batch_op.drop_index('idx_bucket_tour')
        batch_op.drop_index('idx_bucket_event')
        batch_op.drop_index('idx_bucket_created')

    with op.batch_alter_table('leagues', schema=None) as batch_op:
        batch_op.drop_index('idx_league_tour')
        batch_op.drop_index('idx_league_status')
        batch_op.drop_index('idx_league_public')
        batch_op.drop_index('idx_league_payout')
        batch_op.drop_index('idx_league_fees')
        batch_op.drop_index('idx_league_dates')
        batch_op.drop_index('idx_league_creator')
        batch_op.drop_index('idx_league_code')
        batch_op.drop_index('idx_league_club')
        batch_op.drop_index('idx_league_active')

    with op.batch_alter_table('league_entries', schema=None) as batch_op:
        batch_op.drop_index('idx_entry_user')
        batch_op.drop_index('idx_entry_players')
        batch_op.drop_index('idx_entry_league_user')
        batch_op.drop_index('idx_entry_league')
        batch_op.drop_index('idx_entry_fee_status')
        batch_op.drop_index('idx_entry_created')

    with op.batch_alter_table('daily_task_tracker', schema=None) as batch_op:
        batch_op.drop_index('idx_task_date')
        batch_op.drop_index('idx_task_created')

    with op.batch_alter_table('clubs', schema=None) as batch_op:
        batch_op.drop_index('idx_club_name')
        batch_op.drop_index('idx_club_email')
        batch_op.drop_index('idx_club_active')

    op.create_table('push_subscription',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('subscription_json', sa.TEXT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('push_subscription_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('push_subscription_pkey'))
    )
    with op.batch_alter_table('push_subscriptions', schema=None) as batch_op:
        batch_op.drop_index('idx_push_user')

    op.drop_table('push_subscriptions')
    # ### end Alembic commands ###
