"""Added tips to clubs

Revision ID: cd5ff252b07f
Revises: 1e28fab99068
Create Date: 2025-10-08 11:44:11.699166

"""
from sqlalchemy import inspect
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = 'cd5ff252b07f'
down_revision = '1e28fab99068'
branch_labels = None
depends_on = None




def upgrade():
    bind = op.get_bind()
    inspector = inspect(bind)
    columns = [col['name'] for col in inspector.get_columns('clubs')]

    if 'tips_dismissed' not in columns:
        with op.batch_alter_table('clubs', schema=None) as batch_op:
            batch_op.add_column(sa.Column('tips_dismissed', sa.JSON(), nullable=True))
    else:
        print("⚠️ Skipping add_column: 'tips_dismissed' already exists.")


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification_templates', schema=None) as batch_op:
        batch_op.drop_index('idx_template_name')

    with op.batch_alter_table('league_templates', schema=None) as batch_op:
        batch_op.drop_index('idx_template_name')

    with op.batch_alter_table('clubs', schema=None) as batch_op:
        batch_op.drop_column('tips_dismissed')

    # ### end Alembic commands ###
