"""Add notification fields

Revision ID: d224b896cced
Revises: eac570dac3a4
Create Date: 2025-10-05 17:32:50.006891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd224b896cced'
down_revision = 'eac570dac3a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification_preferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tee_time_alerts', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('deadline_alerts', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('friend_activity', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification_preferences', schema=None) as batch_op:
        batch_op.drop_column('friend_activity')
        batch_op.drop_column('deadline_alerts')
        batch_op.drop_column('tee_time_alerts')

    # ### end Alembic commands ###
