"""Added tips to clubs

Revision ID: d7ea8b46bdf7
Revises: 87a6bcb58a8e
Create Date: 2025-10-07 16:31:22.791697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7ea8b46bdf7'
down_revision = '87a6bcb58a8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clubs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tips_dismissed', sa.JSON(), nullable=True))

    # Check if index exists before creating it
    conn = op.get_bind()
    result = conn.execute(sa.text(
        "SELECT 1 FROM pg_indexes WHERE indexname = 'idx_template_name'"
    ))
    index_exists = result.fetchone() is not None

    if not index_exists:
        with op.batch_alter_table('league_templates', schema=None) as batch_op:
            batch_op.create_index('idx_template_name', ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('league_templates', schema=None) as batch_op:
        batch_op.drop_index('idx_template_name')

    with op.batch_alter_table('clubs', schema=None) as batch_op:
        batch_op.drop_column('tips_dismissed')

    # ### end Alembic commands ###
