"""Updated league model. Added tour column

Revision ID: e2e79d65f0f3
Revises: 344766eb95fe
Create Date: 2025-08-07 15:42:56.684235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2e79d65f0f3'
down_revision = '344766eb95fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leagues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tour', sa.String(length=10), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leagues', schema=None) as batch_op:
        batch_op.drop_column('tour')

    # ### end Alembic commands ###
