"""Add player_bucket_id to League and tie-breaker fields

Revision ID: e85c2e6beb50
Revises: 9f7515b76fc0
Create Date: 2025-07-21 13:20:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e85c2e6beb50'
down_revision = '9f7515b76fc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('league_entries', schema=None) as batch_op:
        # This column already exists from a previous partial run.
        # We only need to alter its type if it's not already Integer.
        # IMPORTANT: Added postgresql_using for safe type casting
        batch_op.alter_column('tie_breaker_answer',
                   existing_type=sa.Text(), # Use sa.Text() as a general existing type if unsure
                   type_=sa.Integer(),
                   existing_nullable=True,
                   nullable=True,
                   postgresql_using='NULLIF(tie_breaker_answer, \'\')::integer') # Ensure correct indentation and quotes

    with op.batch_alter_table('leagues', schema=None) as batch_op:
        # REMOVED: batch_op.add_column(sa.Column('tie_breaker_question', sa.String(length=255), nullable=False, server_default='How many total shots will Rory McIlroy take to complete the 4 days of the tournament?'))
        # This column also exists from a previous partial run.
        # REMOVED: batch_op.add_column(sa.Column('player_bucket_id', sa.Integer(), nullable=True))
        # This column also exists from a previous partial run.
        # We only need to ensure the foreign key is created.
        batch_op.create_foreign_key(batch_op.f('fk_leagues_player_bucket_id_player_buckets'), 'player_buckets', ['player_bucket_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leagues', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_leagues_player_bucket_id_player_buckets'), type_='foreignkey')
        batch_op.drop_column('player_bucket_id')
        batch_op.drop_column('tie_breaker_question')

    with op.batch_alter_table('league_entries', schema=None) as batch_op:
        batch_op.drop_column('tie_breaker_answer')

    # ### end Alembic commands ###
