"""Add onboarding fields

Revision ID: eac570dac3a4
Revises: 4fddb73d0628
Create Date: 2025-10-05 01:58:03.405921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eac570dac3a4'
down_revision = '4fddb73d0628'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leagues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_beginner_friendly', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('difficulty_level', sa.String(length=20), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tutorial_completed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('onboarding_step', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('first_login', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('tips_dismissed', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('tips_dismissed')
        batch_op.drop_column('first_login')
        batch_op.drop_column('onboarding_step')
        batch_op.drop_column('tutorial_completed')

    with op.batch_alter_table('leagues', schema=None) as batch_op:
        batch_op.drop_column('difficulty_level')
        batch_op.drop_column('is_beginner_friendly')

    # ### end Alembic commands ###
