"""Add dynamic tie-breaker fields

Revision ID: ece4c0e9a159
Revises: 5087c4e1f9dc
Create Date: 2025-08-15 14:18:01.905340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ece4c0e9a159'
down_revision = '5087c4e1f9dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leagues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tie_breaker_player_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('player_buckets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_id', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_buckets', schema=None) as batch_op:
        batch_op.drop_column('event_id')

    with op.batch_alter_table('leagues', schema=None) as batch_op:
        batch_op.drop_column('tie_breaker_player_id')

    # ### end Alembic commands ###
