"""Add fees_processed to League model

Revision ID: ef4ab1f20b9f
Revises: 066435ee5a26
Create Date: 2025-09-16 13:41:38.190522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef4ab1f20b9f'
down_revision = '066435ee5a26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leagues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fees_processed', sa.Boolean(), nullable=False, server_default='false'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leagues', schema=None) as batch_op:
        batch_op.drop_column('fees_processed')

    # ### end Alembic commands ###
