"""Add current_rank to LeagueEntry model

Revision ID: fa2c0e92c330
Revises: 7156eb5816ad
Create Date: 2025-08-19 20:32:38.949006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa2c0e92c330'
down_revision = '7156eb5816ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('league_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_rank', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('league_entries', schema=None) as batch_op:
        batch_op.drop_column('current_rank')

    # ### end Alembic commands ###
