"""Add tour to PlayerBucket model

Revision ID: fbfe32bcca6d
Revises: fa2c0e92c330
Create Date: 2025-08-20 20:29:05.048341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbfe32bcca6d'
down_revision = 'fa2c0e92c330'
branch_labels = None
depends_on = None


def upgrade():
     # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_buckets', schema=None) as batch_op:
        # --- THIS IS THE FIX ---
        # The column definition is now correctly wrapped in a sa.Column() object
        batch_op.add_column(sa.Column('tour', sa.String(length=10), nullable=False, server_default='pga'))
        # --- END OF FIX ---

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_buckets', schema=None) as batch_op:
        batch_op.drop_column('tour')

    # ### end Alembic commands ###
