"""Add entry_name to LeagueEntry model

Revision ID: fc5774c238b7
Revises: 5c0f159bb48e
Create Date: 2025-07-22 21:29:06.607651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc5774c238b7'
down_revision = '5c0f159bb48e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('league_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entry_name', sa.String(length=150), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('league_entries', schema=None) as batch_op:
        batch_op.drop_column('entry_name')

    # ### end Alembic commands ###
